#!/bin/bash

mkdir /tmp/build_llvm
cd /tmp/build_llvm

git clone /git/llvm

mkdir llvm-build
cd llvm-build

cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DLLVM_CCACHE_BUILD=OFF -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" '-DLLVM_APPEND_VC_REV:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_FFI:BOOL=OFF' '-DLLVM_BUILD_DOCS:BOOL=OFF' '-DLLVM_ENABLE_SPHINX:BOOL=OFF' '-DSPHINX_OUTPUT_HTML:BOOL=OFF' '-DSPHINX_OUTPUT_MAN:BOOL=OFF' '-DSPHINX_WARNINGS_AS_ERRORS:BOOL=OFF' '-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON' '-DLLVM_LINK_LLVM_DYLIB:BOOL=ON' '-DLLVM_BINUTILS_INCDIR:PATH=/usr/include' '-DLLVM_VERSION_SUFFIX=git' '-DLLVM_ENABLE_OCAMLDOC=OFF' '-DLLVM_TARGETS_TO_BUILD=X86;AMDGPU' ../llvm 
ninja
ninja install


cd /
rm -Rf /tmp/build_llvm



